Repository green-fox-academy/JSA-Mawsitsit, pull requests merged in 2019-12, with the labels that each got.

#22 build(JSAM-43):drawer menu
  JSA-Mawsitsit-Frontend/package-lock.json
  JSA-Mawsitsit-Frontend/package.json
  JSA-Mawsitsit-Frontend/src/components/Menu/HamburgerButton.js
  JSA-Mawsitsit-Frontend/src/components/Menu/Menu.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/MenuItem.js
  JSA-Mawsitsit-Frontend/src/navigation/AppNavigation.js
  JSA-Mawsitsit-Frontend/src/styles/MenuStyle.js
Labels: enhancement 🆙🆙🆙

#24 build(JSAM-60):add redux store
  JSA-Mawsitsit-Frontend/App.js
  JSA-Mawsitsit-Frontend/package.json
  JSA-Mawsitsit-Frontend/src/reducers/rootReducer.js
  JSA-Mawsitsit-Frontend/src/screens/RegisterScreen.js
  JSA-Mawsitsit-Frontend/src/store/createStore.js
  JSA-Mawsitsit-Frontend/src/styles/RegisterStyle.js
  JSA-Mawsitsit-Frontend/test/Register.test.js
  JSA-Mawsitsit-Frontend/yarn.lock
Labels: enhancement 🆙🆙🆙

#25 build(JSAM-55): update pm2 config to use rds
  JSA-Mawsitsit-Backend/ecosystem.config.js
  JSA-Mawsitsit-Frontend/package-lock.json
Labels: enhancement 🆙🆙🆙

#30 build(JSAM-67): add birthday into table user_detail
  JSA-Mawsitsit-Backend/migrations/1574852722767_create_table_user_detail.js
Labels: hot fix 🔥🔥🔥

#29 Cola email verification
  JSA-Mawsitsit-Backend/package-lock.json
  JSA-Mawsitsit-Backend/package.json
  JSA-Mawsitsit-Backend/routes/emailVerificationRouter.js
  JSA-Mawsitsit-Backend/routes/personalDetailsRouter.js
  JSA-Mawsitsit-Backend/server.js
  JSA-Mawsitsit-Backend/services/dataService.js
  JSA-Mawsitsit-Frontend/package-lock.json
  JSA-Mawsitsit-Frontend/src/components/Menu/Menu.js
Labels: enhancement 🆙🆙🆙

#27 feat(JSAM-19): build personal detail page
  JSA-Mawsitsit-Frontend/.eslintrc
  JSA-Mawsitsit-Frontend/App.js
  JSA-Mawsitsit-Frontend/package-lock.json
  JSA-Mawsitsit-Frontend/package.json
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/InfoModificationPage.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/Personal.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/PersonalForm.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/SliderBar.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/actions/PersonalAction.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/reducers/PersonalReducer.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/reducers/index.js
  JSA-Mawsitsit-Frontend/src/components/App/ActionTypes.js
  JSA-Mawsitsit-Frontend/src/components/App/AppReducer.js
  JSA-Mawsitsit-Frontend/src/components/App/RootUtilities.js
  JSA-Mawsitsit-Frontend/src/components/Login/Footer.js
  JSA-Mawsitsit-Frontend/src/components/Menu/HamburgerButton.js
  JSA-Mawsitsit-Frontend/src/components/Menu/Menu.js
  JSA-Mawsitsit-Frontend/src/components/Register/Footer.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/IconInput.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/IconListItem.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/LinkButton.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/ProgressBar.js
  JSA-Mawsitsit-Frontend/src/navigation/AppNavigation.js
  JSA-Mawsitsit-Frontend/src/reducers/rootReducer.js
  JSA-Mawsitsit-Frontend/src/screens/AccountManagementScreen.js
  JSA-Mawsitsit-Frontend/src/screens/LoginScreen.js
  JSA-Mawsitsit-Frontend/src/screens/RegisterScreen.js
  JSA-Mawsitsit-Frontend/src/store/appStore.js
  JSA-Mawsitsit-Frontend/src/store/createStore.js
  JSA-Mawsitsit-Frontend/src/styles/IconInputStyle.js
  JSA-Mawsitsit-Frontend/src/styles/IconListItemStyle.js
  JSA-Mawsitsit-Frontend/src/styles/InfoModificationPageStyle.js
  JSA-Mawsitsit-Frontend/src/styles/LinkButtonStyle.js
  JSA-Mawsitsit-Frontend/src/styles/LoginStyle.js
  JSA-Mawsitsit-Frontend/src/styles/PersonalStyle.js
  JSA-Mawsitsit-Frontend/src/styles/ProgressBarStyle.js
  JSA-Mawsitsit-Frontend/src/styles/RegisterStyle.js
Labels: do not merge yet ✋✋✋, enhancement 🆙🆙🆙

#28 build(JSAM-53):connect login button with backend
  JSA-Mawsitsit-Backend/package.json
  JSA-Mawsitsit-Backend/server.js
  JSA-Mawsitsit-Backend/services/validation.js
  JSA-Mawsitsit-Backend/yarn.lock
  JSA-Mawsitsit-Frontend/package.json
  JSA-Mawsitsit-Frontend/src/actions/loginAction.js
  JSA-Mawsitsit-Frontend/src/components/App/AppReducer.js
  JSA-Mawsitsit-Frontend/src/components/Login/Input.js
  JSA-Mawsitsit-Frontend/src/components/Login/LoginForm.js
  JSA-Mawsitsit-Frontend/src/components/Menu/HamburgerButton.js
  JSA-Mawsitsit-Frontend/src/components/Register/Footer.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/InputText.js
  JSA-Mawsitsit-Frontend/src/containers/loginFormContainer.js
  JSA-Mawsitsit-Frontend/src/navigation/AppNavigation.js
  JSA-Mawsitsit-Frontend/src/reducers/loginButtonReducer.js
  JSA-Mawsitsit-Frontend/src/reducers/loginInputReducer.js
  JSA-Mawsitsit-Frontend/src/reducers/loginReducer.js
  JSA-Mawsitsit-Frontend/src/screens/LoginScreen.js
  JSA-Mawsitsit-Frontend/src/screens/RegisterScreen.js
  JSA-Mawsitsit-Frontend/src/screens/WelcomeScreen.js
  JSA-Mawsitsit-Frontend/test/Login.test.js
  JSA-Mawsitsit-Frontend/test/vaildation.test.js
  JSA-Mawsitsit-Frontend/validation/validation.js
  JSA-Mawsitsit-Frontend/yarn.lock
Labels: enhancement 🆙🆙🆙, hot fix 🔥🔥🔥

#32 build(JSAM-68):Login screen visual feedback on login error
  JSA-Mawsitsit-Frontend/src/components/App/AppReducer.js
  JSA-Mawsitsit-Frontend/src/components/Login/LoginForm.js
  JSA-Mawsitsit-Frontend/src/components/Login/actions/loginAction.js
  JSA-Mawsitsit-Frontend/src/components/Login/reducers/loginButtonReducer.js
  JSA-Mawsitsit-Frontend/src/components/Login/reducers/loginInputReducer.js
  JSA-Mawsitsit-Frontend/src/components/Login/reducers/loginReducer.js
  JSA-Mawsitsit-Frontend/src/components/Menu/Menu.js
  JSA-Mawsitsit-Frontend/src/containers/loginFormContainer.js
  JSA-Mawsitsit-Frontend/src/styles/LoginStyle.js
  JSA-Mawsitsit-Frontend/src/styles/MenuStyle.js
Labels: enhancement 🆙🆙🆙

#33 Cola connect email verification
  JSA-Mawsitsit-Backend/migrations/1574644820304_insert_data_user.js
  JSA-Mawsitsit-Backend/migrations/1574852771645_insert_data_user_detail.js
  JSA-Mawsitsit-Backend/routes/emailVerificationRouter.js
  JSA-Mawsitsit-Backend/server.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/InfoModificationPage.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/PersonalForm.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/actions/PersonalAction.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/reducers/PersonalReducer.js
  JSA-Mawsitsit-Frontend/src/components/App/RootUtilities.js
  JSA-Mawsitsit-Frontend/src/components/VerificationPage/Footer.js
  JSA-Mawsitsit-Frontend/src/navigation/AppNavigation.js
  JSA-Mawsitsit-Frontend/src/screens/VerificationScreen.js
  JSA-Mawsitsit-Frontend/src/screens/WelcomeScreen.js
  JSA-Mawsitsit-Frontend/src/styles/VerificationStyle.js
Labels: enhancement 🆙🆙🆙

#34 feat(JSAM-77): optimize sign up page and connect new email verification page
  JSA-Mawsitsit-Backend/routes/emailVerificationRouter.js
  JSA-Mawsitsit-Frontend/App.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/actions/PersonalAction.js
  JSA-Mawsitsit-Frontend/src/components/App/ActionTypes.js
  JSA-Mawsitsit-Frontend/src/components/App/AppReducer.js
  JSA-Mawsitsit-Frontend/src/components/App/RootUtilities.js
  JSA-Mawsitsit-Frontend/src/components/App/Validations.js
  JSA-Mawsitsit-Frontend/src/components/Register/PasswordStrength.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/IconInput.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/EmailVerification.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/Footer.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/PasswordStrengthBar.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/SignUp.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/SignUpForm.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/actions/SignUpAction.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/reducers/index.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/styles/EmailVerificationStyle.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/styles/PasswordStrengthBarStyle.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/styles/SignUpFormStyle.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/styles/SignUpStyle.js
  JSA-Mawsitsit-Frontend/src/navigation/AppNavigation.js
  JSA-Mawsitsit-Frontend/src/screens/RegisterScreen.js
  JSA-Mawsitsit-Frontend/src/screens/VerificationScreen.js
  JSA-Mawsitsit-Frontend/src/styles/IconInputStyle.js
  JSA-Mawsitsit-Frontend/src/styles/RegisterStyle.js
  JSA-Mawsitsit-Frontend/test/PasswordStrengthBar.test.js
  JSA-Mawsitsit-Frontend/test/Register.test.js
Labels: enhancement 🆙🆙🆙

#35 fix(JSAM-68):change the style of login form
  JSA-Mawsitsit-Frontend/App.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/Personal.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/PersonalForm.js
  JSA-Mawsitsit-Frontend/src/components/App/RootUtilities.js
  JSA-Mawsitsit-Frontend/src/components/App/Validations.js
  JSA-Mawsitsit-Frontend/src/components/Login/LoginForm.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/IconInput.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/EmailVerification.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/SignUp.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/reducers/index.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/styles/SignUpStyle.js
  JSA-Mawsitsit-Frontend/src/components/VerificationPage/Footer.js
  JSA-Mawsitsit-Frontend/src/navigation/AppNavigation.js
  JSA-Mawsitsit-Frontend/src/screens/LoginScreen.js
  JSA-Mawsitsit-Frontend/src/styles/LoginStyle.js
Labels: hot fix 🔥🔥🔥

#36 feat(JSAM-21): build secure page
  JSA-Mawsitsit-Backend/routes/personalDetailsRouter.js
  JSA-Mawsitsit-Backend/routes/personalRouter.js
  JSA-Mawsitsit-Backend/routes/registerRouter.js
  JSA-Mawsitsit-Backend/server.js
  JSA-Mawsitsit-Backend/services/dataService.js
  JSA-Mawsitsit-Backend/services/personalDataService.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/AccountManagement.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/InfoModificationPage.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/Personal/Personal.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/Personal/PersonalForm.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/Secure/Secure.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/SliderBar.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/actions/PersonalAction.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/actions/SecureAction.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/reducers/PersonalReducer.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/reducers/SecureReducer.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/reducers/index.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/styles/AccountManagementStyle.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/styles/InfoModificationPageStyle.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/styles/PersonalStyle.js
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/styles/SecureStyle.js
  JSA-Mawsitsit-Frontend/src/components/App/ActionTypes.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/IconListItem.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/ProgressBar.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/styles/IconListItemStyle.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/styles/ProgressBarStyle.js
  JSA-Mawsitsit-Frontend/src/components/VerificationPage/Footer.js
  JSA-Mawsitsit-Frontend/src/navigation/AppNavigation.js
  JSA-Mawsitsit-Frontend/src/screens/AccountManagementScreen.js
Labels: hot fix 🔥🔥🔥

#37 FINAL CUT ~~~~~~~~
  JSA-Mawsitsit-Frontend/src/components/AccountManagement/Secure/Secure.js
  JSA-Mawsitsit-Frontend/src/components/First/Footer.js
  JSA-Mawsitsit-Frontend/src/components/Login/Footer.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/EmailVerification.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/styles/EmailVerificationStyle.js
  JSA-Mawsitsit-Frontend/src/components/SignUp/styles/SignUpStyle.js
  JSA-Mawsitsit-Frontend/src/styles/FirstStyle.js
Labels: hot fix 🔥🔥🔥
