Repository green-fox-academy/JSA-Mawsitsit, pull requests merged in 2019-11, with the labels that each got.

#5 build(JSAM-32): configure git commit hook with husky and lerna
  .gitignore
  JSA-Mawsitsit-Backend/.eslintrc
  JSA-Mawsitsit-Backend/Database.js
  JSA-Mawsitsit-Backend/Migration.js
  JSA-Mawsitsit-Backend/Server.js
  JSA-Mawsitsit-Backend/package-lock.json
  JSA-Mawsitsit-Backend/package.json
  JSA-Mawsitsit-Frontend/.eslintrc
  JSA-Mawsitsit-Frontend/babel.config.js
  lerna.json
  package-lock.json
  package.json
Labels: enhancement

#8 build(JSAM-16): create EC2 instance and deploy app through pm2
  JSA-Mawsitsit-Backend/ecosystem.config.js
  JSA-Mawsitsit-Backend/package-lock.json
  JSA-Mawsitsit-Backend/package.json
Labels: enhancement

#7 Build(JSAM-2):Register frontend
  .gitignore
  JSA-Mawsitsit-Frontend/.eslintrc
  JSA-Mawsitsit-Frontend/App.js
  JSA-Mawsitsit-Frontend/components/Register/PasswordStrength.js
  JSA-Mawsitsit-Frontend/components/Register/Register.js
  JSA-Mawsitsit-Frontend/components/Register/Styles.js
  JSA-Mawsitsit-Frontend/package-lock.json
  JSA-Mawsitsit-Frontend/package.json
  JSA-Mawsitsit-Frontend/test/PasswordStrength.test.js
  JSA-Mawsitsit-Frontend/test/Register.test.js
  JSA-Mawsitsit-Frontend/validation/validation.js
  JSA-Mawsitsit-Frontend/yarn.lock
Labels: enhancement

#9 fix(JSAM-16): add PORT as an env variable for pm2
  JSA-Mawsitsit-Backend/ecosystem.config.js
Labels: fix

#10 feat (JSAM-41): add react-navigation and related headers
  JSA-Mawsitsit-Frontend/App.js
  JSA-Mawsitsit-Frontend/components/App/AppNavigation.js
  JSA-Mawsitsit-Frontend/components/PersonalDetails/PersonalDetails.js
  JSA-Mawsitsit-Frontend/components/Register/Register.js
  JSA-Mawsitsit-Frontend/package-lock.json
  JSA-Mawsitsit-Frontend/package.json
Labels: enhancement

#13 build(JSAM-26):Extend register with database
  JSA-Mawsitsit-Backend/database.js
  JSA-Mawsitsit-Backend/migration.js
  JSA-Mawsitsit-Backend/migrations/1574503754586_create_table_users.js
  JSA-Mawsitsit-Backend/migrations/1574644820304_create_table_users.js
  JSA-Mawsitsit-Frontend/package.json
  JSA-Mawsitsit-Frontend/yarn.lock
Labels: enhancement

#14 fix(JSAM-26):fix SQL syntax
  JSA-Mawsitsit-Backend/migrations/1574503754586_create_table_users.js
  JSA-Mawsitsit-Backend/migrations/1574644820304_create_table_users.js
  JSA-Mawsitsit-Frontend/yarn.lock
Labels: fix

#12 build(JSAM-17): Login frontend
  JSA-Mawsitsit-Frontend/App.js
  JSA-Mawsitsit-Frontend/components/Register/Register.js
  JSA-Mawsitsit-Frontend/components/Register/Styles.js
  JSA-Mawsitsit-Frontend/package-lock.json
  JSA-Mawsitsit-Frontend/package.json
  JSA-Mawsitsit-Frontend/src/components/Login/Footer.js
  JSA-Mawsitsit-Frontend/src/components/Login/Header.js
  JSA-Mawsitsit-Frontend/src/components/Login/Input.js
  JSA-Mawsitsit-Frontend/src/components/PersonalDetails/PersonalDetails.js
  JSA-Mawsitsit-Frontend/src/components/Register/Footer.js
  JSA-Mawsitsit-Frontend/src/components/Register/PasswordStrength.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/InputText.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/LinkButton.js
  JSA-Mawsitsit-Frontend/src/components/SharedUnits/Select.js
  JSA-Mawsitsit-Frontend/src/navigation/AppNavigation.js
  JSA-Mawsitsit-Frontend/src/screens/LoginScreen.js
  JSA-Mawsitsit-Frontend/src/screens/RegisterScreen.js
  JSA-Mawsitsit-Frontend/src/styles/LoginStyle.js
  JSA-Mawsitsit-Frontend/src/styles/RegisterStyle.js
  JSA-Mawsitsit-Frontend/test/Login.test.js
  JSA-Mawsitsit-Frontend/test/PasswordStrength.test.js
  JSA-Mawsitsit-Frontend/test/Register.test.js
Labels: enhancement

#17 fix(JSAM-17):implement of registerStyle
  JSA-Mawsitsit-Frontend/src/styles/RegisterStyle.js
Labels: fix

#16 feat(JSAM-42): implement database actions for login
  JSA-Mawsitsit-Backend/.eslintrc
  JSA-Mawsitsit-Backend/Users.js
  JSA-Mawsitsit-Backend/database.js
  JSA-Mawsitsit-Backend/ecosystem.config.js
  JSA-Mawsitsit-Backend/migrations/1574644820304_create_table_users.js
  JSA-Mawsitsit-Backend/package.json
  JSA-Mawsitsit-Backend/routes/loginRouter.js
  JSA-Mawsitsit-Backend/services/__mocks__/dataService.js
  JSA-Mawsitsit-Backend/services/checkLogin.js
  JSA-Mawsitsit-Backend/services/dataService.js
  JSA-Mawsitsit-Backend/services/validation.js
  JSA-Mawsitsit-Backend/tests/loginRoutes.test.js
  JSA-Mawsitsit-Backend/tests/registerRoutes.test.js
  JSA-Mawsitsit-Frontend/package-lock.json
Labels: enhancement, environment

#19 build(JSAM-54):JWT token is sent to frontend on successful login
  JSA-Mawsitsit-Backend/package.json
  JSA-Mawsitsit-Backend/routes/loginRouter.js
  JSA-Mawsitsit-Backend/routes/registerRouter.js
  JSA-Mawsitsit-Backend/services/dataService.js
  JSA-Mawsitsit-Backend/services/validation.js
  JSA-Mawsitsit-Backend/tests/loginRoutes.test.js
  JSA-Mawsitsit-Backend/tests/registerRoutes.test.js
  JSA-Mawsitsit-Backend/yarn.lock
  JSA-Mawsitsit-Frontend/package-lock.json
  JSA-Mawsitsit-Frontend/yarn.lock
Labels: enhancement

#18 build(JSAM-51): Create a slider bar into personal details screen
  JSA-Mawsitsit-Frontend/src/components/PersonalDetails/SliderBar.js
  JSA-Mawsitsit-Frontend/src/navigation/AppNavigation.js
  JSA-Mawsitsit-Frontend/src/screens/AccountManagementScreen.js
  JSA-Mawsitsit-Frontend/src/screens/RegisterScreen.js
  JSA-Mawsitsit-Frontend/src/styles/PersonalDetailsStyle.js
Labels: enhancement

#21 build(JSAM-59):password encryption
  JSA-Mawsitsit-Backend/migrations/1574503754586_create_table_user.js
  JSA-Mawsitsit-Backend/migrations/1574503754586_create_table_users.js
  JSA-Mawsitsit-Backend/migrations/1574644820304_create_table_users.js
  JSA-Mawsitsit-Backend/migrations/1574644820304_insert_data_user.js
  JSA-Mawsitsit-Backend/package.json
  JSA-Mawsitsit-Backend/routes/loginRouter.js
  JSA-Mawsitsit-Backend/routes/registerRouter.js
  JSA-Mawsitsit-Backend/services/__mocks__/dataService.js
  JSA-Mawsitsit-Backend/services/dataService.js
  JSA-Mawsitsit-Backend/services/validation.js
  JSA-Mawsitsit-Backend/tests/registerRoutes.test.js
  JSA-Mawsitsit-Backend/tests/validation.test.js
  JSA-Mawsitsit-Backend/yarn.lock
Labels: enhancement 🆙🆙🆙

#20 feat(JSAM-58): create 'authMiddleware' for route requests protecting
  JSA-Mawsitsit-Backend/middleware/auth.js
  JSA-Mawsitsit-Backend/package-lock.json
  JSA-Mawsitsit-Backend/routes/loginRouter.js
  JSA-Mawsitsit-Backend/tests/authMiddleware.test.js
Labels: enhancement 🆙🆙🆙

#23 feat(JSAM-50): extend register user endpoint to save user detail data
  JSA-Mawsitsit-Backend/migrations/1574852722767_create_table_user_detail.js
  JSA-Mawsitsit-Backend/migrations/1574852771645_insert_data_user_detail.js
  JSA-Mawsitsit-Backend/routes/loginRouter.js
  JSA-Mawsitsit-Backend/routes/registerRouter.js
  JSA-Mawsitsit-Backend/services/__mocks__/dataService.js
  JSA-Mawsitsit-Backend/services/dataService.js
  JSA-Mawsitsit-Backend/tests/loginRoutes.test.js
  JSA-Mawsitsit-Backend/tests/validation.test.js
Labels: enhancement 🆙🆙🆙
